[wokwi]
version = 1
firmware = "../../../.arduino/output/DetectPressAndReleaseNonBlockingMultipleFunctions.ino.hex"
elf = "../../../.arduino/output/DetectPressAndReleaseNonBlockingMultipleFunctions.ino.elf"
